name: Flutter Web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout da branch
      uses: actions/checkout@v2
    - name: Inicializar Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Inicializando Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        channel: 'stable'
    - name: Resolver dependencias
      run: flutter pub get
#     - name: Rodar Testes
#       run: flutter test

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout da branch
      uses: actions/checkout@v2
    - name: Inicializar Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Inicializando Flutter
      uses: subosito/flutter-action@v1.3.2
      with:
        flutter-version: '1.18.0-11.1.pre' 
        channel: 'beta'
    - name: Habilitar ambiente Web
      run: flutter config --enable-web
    - name: Resolver dependencias
      run: flutter pub get
#     - name: Rodar Testes
#       run: flutter test
    - name: Buildar um Flutter Web Release
      run: flutter build web --release
    - name: Copiar build do Web para pasta do Github Pages
      run: cp -R ./build/web/* ./docs
    - name: Publicar projecto Web na branch de master
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Deploy Web'
        force-add: 'true'
        files: ./docs/*
        name: Github Actions
        email: mtorreao1@gmail.com
