name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  cirrusci/flutter:beta

    steps:
    - name: Permissao a pasta que o github actions usa
      run: chmod -R 777 /__w/smartgoalfront/smartgoalfront
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.PAT }}
    - name: Install dependencies
      run: flutter pub get
    - name: Build a Flutter Web Release
      run: flutter build web --release
    - name: Copiar conteudo da pasta Web
      run: cp -r ./build/web/* ./docs
